version: '3.9'
services:
  db:
    image: postgres
    restart: always 
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    restart: always 
    command: sh -c "make migrate && make createsuperuser && make run"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:${WEB_PORT}:8000"
    depends_on:
      - db
volumes:
  postgres_data: