# Generated by Django 4.2.19 on 2025-02-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='additional_info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Дополнительная информация'),
        ),
    ]
